<?php 
	/*
		This php file is taking the board created by players as an Array, '$Array', with Board Cell Numbers Ranging from 1-100 as its keys and Ship sizes as its Values. It stores the Array as a Table, 'Board_<id>', in the Database 'Battleship', where <id> is a random number generated by a Random function which is not part of other Board present in the Database.
	*/
	// $jArray takes the Board sent from setup.html
	$jArray = $_POST['hiddenF'];
	// Connection to the Server and Database 'Battleship'
	$mysqli = new mysqli("localhost", "root", "", "Battleship");
	$mysqli->query("USE Battleship");
	start:
	// rand() creates the Random id number
	$B_id = rand();
	$Board = "Board_" . $B_id;
	$Board_Using = "BoardUsing_" . $B_id;
	$check = True;
	$result = $mysqli->query("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = \"BASE TABLE\" AND TABLE_SCHEMA=\"Battleship\"");
		if($result->num_rows > 0)
			{
				while($row = $result->fetch_assoc())
					{
						// checks whether the Random id created is unique and not present with any other Boards present in the Database
						if($Board == $row["TABLE_NAME"])
							$check = False;
						if($Board_Using == $row["TABLE_NAME"])
							$check = False;
					}
			}
	mysqli_free_result($result);
		if(!$check)
		{
			// If the Random id matches with already present board then the process starts again
			goto start;
		}
		else
		{
			// else if continues with the Random id to create a Board with it in it
			goto lb;
		}
	lb:
	// creates the Board
	$mysqli->query("CREATE TABLE Board_" . $B_id ." (Positions int NOT NULL, Ship int NOT NULL)");
	// $Array is the final Board Aray to be sent to the server
	$Array = explode(",", $jArray);
		for ($i=1; $i <= 100; $i++) 
		{
			// inserts the Array into the Table created
			$mysqli->query("INSERT INTO Board_" . $B_id . " (Positions , Ship) VALUES ('" . $i . "' , '" . $Array[$i] . "')");
		}
	// Redirects to play_area.php with Random Board id as a variable for Player 1
	header('Location: play_area.php?id1='. $B_id . '&id2=0&id3=0');
 ?>